source 'https://rubygems.org'

gem 'motion-i18n', '0.0.2'
gem 'i18n_tools', '0.1.5', :require => 'i18n_tools/tasks'
gem 'bubble-wrap', '1.3.0'
gem 'sugarcube', '1.0.7', :require => 'sugarcube-classic'
gem 'teacup', '2.1.9'
gem 'sweettea', '0.5.6'
gem 'motion-stump', '0.3.0'
gem 'motion-redgreen', '0.1.0'