source 'https://rubygems.org'

gem 'motion-i18n', '0.0.2'
gem 'i18n_tools', '0.1.6', :require => 'i18n_tools/tasks'
gem 'bubble-wrap', '1.7.0'
gem 'sugarcube', '2.0.1', :require => 'sugarcube-classic'
gem 'teacup', '3.0.0'
gem 'sweettea', '0.6.0'
gem 'motion-stump', '0.3.2'
gem 'motion-redgreen', '0.1.0'
